name: lovely_coffees
description: Lovely coffees
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  carousel_slider: ^5.0.0
  clock: ^1.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.4.1
  http: ^1.2.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  meta: ^1.15.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21